// src/engine/rules.ts
// Compliance Rule Catalog across CIS v8, NIST 800-53, DISA STIG, and ISO 27001
// Each rule evaluates ONLY NormalizedConfig["parameters"] and maps controlGroupId for deduplication (§6.4)

import { ComplianceRule, NormalizedConfig } from "../types/canonical";

export const COMPLIANCE_RULES: ComplianceRule[] = [
  // ─── CIS Controls v8 ───
  {
    id: "CIS-NET-1.1.1",
    title: "Enforce SSHv2 Protocol Exclusively",
    framework: "cis_v8",
    severity: "critical",
    controlGroupId: "CTRL-SSH-V2",
    description: "Legacy SSHv1 protocol possesses cryptographic weaknesses permitting session interception and MITM.",
    frameworkRef: "CIS Controls v8 Safeguard 12.6",
    sourceNote: "CIS Controls v8, Safeguard 12.6 (Use Secure Network Management Protocols - SSHv2)",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend\nwrite memory",
      juniper_junos: "set system services ssh protocol-version v2\ncommit and-quit",
      palo_alto_panos: "set deviceconfig system ssh ciphers mgmt [ aes256-gcm aes256-ctr ]\ncommit",
      sonic: 'sonic-cli -c "configure terminal ; ip ssh version 2"',
      fortinet_fortios: "config system global\nset admin-ssh-v1 disable\nset strong-crypto enable\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.1.2",
    title: "Disable Insecure Telnet Daemon",
    framework: "cis_v8",
    severity: "critical",
    controlGroupId: "CTRL-TELNET-OFF",
    description: "Telnet transmits administrative credentials and session commands in plaintext over the wire.",
    frameworkRef: "CIS Controls v8 Safeguard 4.8 / 12.6",
    sourceNote: "CIS Controls v8, Safeguards 4.8 & 12.6 (Disable Unnecessary Cleartext Services - Telnet)",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend\nwrite memory",
      juniper_junos: "delete system services telnet\ncommit and-quit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: "systemctl mask --now telnet.socket",
      fortinet_fortios: 'config system interface\nedit "port1"\nset allowaccess https ssh ping\nnext\nend',
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.1.3",
    title: "Disable Plaintext HTTP Web Management",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-HTTP-OFF",
    description: "Unencrypted web management consoles expose session cookies and credentials to eavesdropping.",
    frameworkRef: "CIS Controls v8 Safeguard 4.8 / 12.6",
    sourceNote: "CIS Controls v8, Safeguards 4.8 & 12.6 (Disable Insecure Web Management - Mandate HTTPS)",
    evaluate: (p) => (p.httpServerEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno ip http server\nip http secure-server\nend\nwrite memory",
      juniper_junos: "delete system services web-management http\nset system services web-management https port 443\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-http yes\ncommit",
      sonic: "systemctl stop nginx-http && systemctl disable nginx-http",
      fortinet_fortios: "config system global\nset admin-https-redirect enable\nend",
      arista_eos: "configure\nno management api http-commands\nprotocol https\nexit\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.1.4",
    title: "Enforce Strong Local Password Encryption",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-PASS-ENCRYPT",
    description: "Pre-shared secrets and local operator passwords must be secured with irreversible cryptographic ciphers.",
    frameworkRef: "CIS Controls v8 Safeguard 5.2 / 3.11",
    sourceNote: "CIS Controls v8, Safeguards 5.2 & 3.11 (Secure Local Credential Storage - PBKDF2/SHA-512)",
    evaluate: (p) => (p.passwordEncryptionEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nservice password-encryption\nend\nwrite memory",
      juniper_junos: "set system login password-format sha512\ncommit",
      palo_alto_panos: "set mgt-config users secadmin password\ncommit",
      sonic: "passwd -e admin",
      fortinet_fortios: "config system global\nset strong-crypto enable\nend",
      arista_eos: "configure\nservice password-encryption\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.2.1",
    title: "Centralized AAA Authentication Enforcement",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-AAA-AUTH",
    description: "Network devices must defer administrative credential verification to centralized TACACS+ or RADIUS.",
    frameworkRef: "CIS Controls v8 Safeguard 12.5",
    sourceNote: "CIS Controls v8, Safeguard 12.5 (Centralize Network AAA Infrastructure)",
    evaluate: (p) => (p.aaaAuthEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\naaa new-model\naaa authentication login default group tacacs+ local\nend\nwrite memory",
      juniper_junos: "set system authentication-order [ tacplus radius password ]\ncommit",
      palo_alto_panos: "set shared authentication-profile TACACS-AUTH method tacacs-plus\ncommit",
      sonic: "config aaa authentication login tacacs+ local",
      fortinet_fortios: 'config user tacacs+\nedit "tacacs_srv"\nset server "10.14.5.10"\nnext\nend',
      arista_eos: "configure\naaa authentication login default group tacacs+ local\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.2.2",
    title: "SNMP Protocol Restricted to v3 authPriv",
    framework: "cis_v8",
    severity: "critical",
    controlGroupId: "CTRL-SNMP-V3",
    description: "Legacy SNMPv1/v2c relies on cleartext community strings subject to replay and reconnaissance.",
    frameworkRef: "CIS Controls v8 Safeguard 12.6",
    sourceNote: "CIS Controls v8, Safeguard 12.6 (Secure Network Management Protocols - SNMPv3 authPriv)",
    evaluate: (p) => (p.snmpVersion === "v3" ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno snmp-server community public\nsnmp-server group SECGROUP v3 priv\nend\nwrite memory",
      juniper_junos: "delete snmp community\nset snmp v3 usm local-engine user admin-v3 authentication-sha\ncommit",
      palo_alto_panos: "set deviceconfig system snmp-setting snmp-version-v3 user secoper authpwd <pwd> privpwd <pwd>\ncommit",
      sonic: "config snmp user add secoper SHA <auth-key> AES <priv-key>",
      fortinet_fortios: 'config system snmp user\nedit "snmp3user"\nset security-level auth-priv\nnext\nend',
      arista_eos: "configure\nsnmp-server group SECGROUP v3 auth\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.3.1",
    title: "Remote Centralized Syslog Forwarding",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-SYSLOG-SIEM",
    description: "Security telemetry and event logs must be streamed continuously to the SIEM cluster.",
    frameworkRef: "CIS Controls v8 Safeguard 8.2",
    sourceNote: "CIS Controls v8, Safeguard 8.2 (Collect Audit Logs - Centralized Syslog)",
    evaluate: (p) => (p.syslogServers !== null ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nlogging host 10.14.5.50\nlogging trap notifications\nend\nwrite memory",
      juniper_junos: "set system syslog host 10.14.5.50 any warning facility-override local5\ncommit",
      palo_alto_panos: "set shared log-settings syslog SIEM server 10.14.5.50 port 514\ncommit",
      sonic: "config syslog add 10.14.5.50",
      fortinet_fortios: 'config log syslogd setting\nset status enable\nset server "10.14.5.50"\nend',
      arista_eos: "configure\nlogging host 10.14.5.50\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.3.2",
    title: "Terminal Session Idle Timeout Lockout (≤ 15 min)",
    framework: "cis_v8",
    severity: "medium",
    controlGroupId: "CTRL-IDLE-TIMEOUT",
    description: "Unattended management sessions must be terminated automatically after 15 minutes.",
    frameworkRef: "CIS Controls v8 Safeguard 4.3",
    sourceNote: "CIS Controls v8, Safeguard 4.3 (Configure Automatic Session Locking on Enterprise Assets)",
    evaluate: (p) => (p.sessionIdleTimeoutMinutes !== null && Number(p.sessionIdleTimeoutMinutes) <= 15 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline con 0\nexec-timeout 10 0\nline vty 0 15\nexec-timeout 10 0\nend\nwrite memory",
      juniper_junos: "set system login idle-timeout 10\ncommit",
      palo_alto_panos: "set deviceconfig system idle-timeout 10\ncommit",
      sonic: "config ssh idle-timeout 600",
      fortinet_fortios: "config system global\nset admintimeout 10\nend",
      arista_eos: "configure\nmanagement ssh\nidle-timeout 10\nexit\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.4.1",
    title: "Cryptographic NTP Time Synchronization",
    framework: "cis_v8",
    severity: "medium",
    controlGroupId: "CTRL-NTP-SYNC",
    description: "Audit trail defensibility requires all devices synchronize against trusted time references.",
    frameworkRef: "CIS Controls v8 Safeguard 8.4",
    sourceNote: "CIS Controls v8, Safeguard 8.4 (Standardize Time Synchronization across Enterprise Assets)",
    evaluate: (p) => (p.ntpConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nntp server 10.14.0.1 prefer\nntp authenticate\nend\nwrite memory",
      juniper_junos: "set system ntp server 10.14.0.1 prefer\ncommit",
      palo_alto_panos: "set deviceconfig system ntp-servers primary-ntp-server 10.14.0.1\ncommit",
      sonic: "config ntp add 10.14.0.1",
      fortinet_fortios: "config system ntp\nset ntpsync enable\nset type custom\nend",
      arista_eos: "configure\nntp server 10.14.0.1 prefer\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.4.2",
    title: "Authorized Login Notice / Banner Configuration",
    framework: "cis_v8",
    severity: "low",
    controlGroupId: "CTRL-LOGIN-BANNER",
    description: "Statutory notice of authorized government access must be presented before login.",
    frameworkRef: "CIS Controls v8 Safeguard 4.1",
    sourceNote: "CIS Controls v8, Safeguard 4.1 (Establish and Maintain a Secure Configuration Baseline - Advisory Banner)",
    evaluate: (p) => (p.loginBannerConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nbanner login ^C\nRESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY\n^C\nend\nwrite memory",
      juniper_junos: 'set system login message "RESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY"\ncommit',
      palo_alto_panos: 'set deviceconfig system login-banner "RESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY"\ncommit',
      sonic: 'config banner login "RESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY"',
      fortinet_fortios: "config system global\nset pre-login-banner enable\nend",
      arista_eos: "configure\nbanner login\nRESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY\nEOF\nwrite memory",
    },
  },

  // ─── NIST SP 800-53 Rev. 5 Controls ───
  {
    id: "NIST-AC-17",
    title: "Remote Access Encryption Protocol (SSHv2)",
    framework: "nist_800_53",
    severity: "critical",
    controlGroupId: "CTRL-SSH-V2",
    description: "NIST AC-17 mandates FIPS-approved cryptographic protocols for all remote network maintenance.",
    frameworkRef: "NIST SP 800-53 Rev. 5 AC-17(2)",
    sourceNote: "NIST SP 800-53 Rev. 5, Control AC-17(2) (Remote Access - Cryptographic Protection)",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend\nwrite memory",
      juniper_junos: "set system services ssh protocol-version v2\ncommit",
      palo_alto_panos: "set deviceconfig system ssh ciphers mgmt [ aes256-gcm aes256-ctr ]\ncommit",
      sonic: 'sonic-cli -c "configure terminal ; ip ssh version 2"',
      fortinet_fortios: "config system global\nset admin-ssh-v1 disable\nset strong-crypto enable\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit\nwrite memory",
    },
  },
  {
    id: "NIST-SC-8",
    title: "Transmission Confidentiality (Ban Insecure Telnet)",
    framework: "nist_800_53",
    severity: "critical",
    controlGroupId: "CTRL-TELNET-OFF",
    description: "Prohibit transmission of confidential data over unencrypted cleartext transport daemons.",
    frameworkRef: "NIST SP 800-53 Rev. 5 SC-8(1)",
    sourceNote: "NIST SP 800-53 Rev. 5, Control SC-8(1) (Transmission Confidentiality - Disable Cleartext Protocols)",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend\nwrite memory",
      juniper_junos: "delete system services telnet\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: "systemctl mask --now telnet.socket",
      fortinet_fortios: 'config system interface\nedit "port1"\nset allowaccess https ssh ping\nnext\nend',
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "NIST-SC-13",
    title: "Cryptographic Boundary (Disable Plaintext HTTP)",
    framework: "nist_800_53",
    severity: "high",
    controlGroupId: "CTRL-HTTP-OFF",
    description: "Protect web management sessions by disabling unencrypted HTTP interfaces.",
    frameworkRef: "NIST SP 800-53 Rev. 5 SC-13 / SC-8",
    sourceNote: "NIST SP 800-53 Rev. 5, Controls SC-13 & SC-8 (Cryptographic Protection of Management Services)",
    evaluate: (p) => (p.httpServerEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno ip http server\nip http secure-server\nend\nwrite memory",
      juniper_junos: "delete system services web-management http\nset system services web-management https\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-http yes\ncommit",
      sonic: "systemctl stop nginx-http && systemctl disable nginx-http",
      fortinet_fortios: "config system global\nset admin-https-redirect enable\nend",
      arista_eos: "configure\nno management api http-commands\nprotocol https\nexit\nwrite memory",
    },
  },
  {
    id: "NIST-IA-5",
    title: "Authenticator Management (Password Storage Encryption)",
    framework: "nist_800_53",
    severity: "high",
    controlGroupId: "CTRL-PASS-ENCRYPT",
    description: "Enforce cryptographic protection for local authentication secrets stored on network devices.",
    frameworkRef: "NIST SP 800-53 Rev. 5 IA-5(1)",
    sourceNote: "NIST SP 800-53 Rev. 5, Control IA-5(1) (Password-Based Authentication - Cryptographic Storage)",
    evaluate: (p) => (p.passwordEncryptionEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nservice password-encryption\nend\nwrite memory",
      juniper_junos: "set system login password-format sha512\ncommit",
      palo_alto_panos: "set mgt-config users secadmin password\ncommit",
      sonic: "passwd -e admin",
      fortinet_fortios: "config system global\nset strong-crypto enable\nend",
      arista_eos: "configure\nservice password-encryption\nwrite memory",
    },
  },
  {
    id: "NIST-IA-2",
    title: "Identification and Authentication (Centralized AAA)",
    framework: "nist_800_53",
    severity: "high",
    controlGroupId: "CTRL-AAA-AUTH",
    description: "Authenticate network administrators against centralized directory services (TACACS+/RADIUS).",
    frameworkRef: "NIST SP 800-53 Rev. 5 IA-2(1)",
    sourceNote: "NIST SP 800-53 Rev. 5, Control IA-2(1) (Centralized Identification and Authentication)",
    evaluate: (p) => (p.aaaAuthEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\naaa new-model\naaa authentication login default group tacacs+ local\nend\nwrite memory",
      juniper_junos: "set system authentication-order [ tacplus radius password ]\ncommit",
      palo_alto_panos: "set shared authentication-profile TACACS-AUTH method tacacs-plus\ncommit",
      sonic: "config aaa authentication login tacacs+ local",
      fortinet_fortios: 'config user tacacs+\nedit "secops_tacacs"\nset server "10.14.5.10"\nnext\nend',
      arista_eos: "configure\naaa authentication login default group tacacs+ local\nwrite memory",
    },
  },
  {
    id: "NIST-SC-8-SNMP",
    title: "Transmission Integrity (Mandate SNMPv3 authPriv)",
    framework: "nist_800_53",
    severity: "high",
    controlGroupId: "CTRL-SNMP-V3",
    description: "Protect device telemetry and SNMP management transactions using cryptographic algorithms.",
    frameworkRef: "NIST SP 800-53 Rev. 5 SC-8(1)",
    sourceNote: "NIST SP 800-53 Rev. 5, Control SC-8(1) (Cryptographic Protection for Telemetry & Polling)",
    evaluate: (p) => (p.snmpVersion === "v3" ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno snmp-server community public\nsnmp-server group NIST_GRP v3 priv\nend\nwrite memory",
      juniper_junos: "delete snmp community\nset snmp v3 usm local-engine user secadmin authentication-sha\ncommit",
      palo_alto_panos: "set deviceconfig system snmp-setting snmp-version-v3 user secadmin authpwd <pwd> privpwd <pwd>\ncommit",
      sonic: "config snmp user add secadmin SHA <key> AES <key>",
      fortinet_fortios: 'config system snmp user\nedit "secadmin"\nset security-level auth-priv\nnext\nend',
      arista_eos: "configure\nsnmp-server group NIST_GRP v3 auth\nwrite memory",
    },
  },
  {
    id: "NIST-AU-4",
    title: "Audit Storage (Transfer Records to Central SIEM)",
    framework: "nist_800_53",
    severity: "high",
    controlGroupId: "CTRL-SYSLOG-SIEM",
    description: "Stream audit records to an off-device centralized SIEM repository in real time.",
    frameworkRef: "NIST SP 800-53 Rev. 5 AU-4(1) / AU-12",
    sourceNote: "NIST SP 800-53 Rev. 5, Control AU-4(1) (Transfer to Alternate Storage / Central SIEM Repository)",
    evaluate: (p) => (p.syslogServers !== null ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nlogging host 10.14.5.50\nend\nwrite memory",
      juniper_junos: "set system syslog host 10.14.5.50 any warning\ncommit",
      palo_alto_panos: "set shared log-settings syslog SIEM server 10.14.5.50 port 514\ncommit",
      sonic: "config syslog add 10.14.5.50",
      fortinet_fortios: 'config log syslogd setting\nset server "10.14.5.50"\nend',
      arista_eos: "configure\nlogging host 10.14.5.50\nwrite memory",
    },
  },
  {
    id: "NIST-AC-12",
    title: "Session Termination (Inactivity Disconnect ≤ 15 min)",
    framework: "nist_800_53",
    severity: "medium",
    controlGroupId: "CTRL-IDLE-TIMEOUT",
    description: "Automatically terminate inactive administrative terminal sessions after 15 minutes.",
    frameworkRef: "NIST SP 800-53 Rev. 5 AC-12",
    sourceNote: "NIST SP 800-53 Rev. 5, Control AC-12 (Session Termination)",
    evaluate: (p) => (p.sessionIdleTimeoutMinutes !== null && Number(p.sessionIdleTimeoutMinutes) <= 15 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\nexec-timeout 10 0\nend\nwrite memory",
      juniper_junos: "set system login idle-timeout 10\ncommit",
      palo_alto_panos: "set deviceconfig system idle-timeout 10\ncommit",
      sonic: "config ssh idle-timeout 600",
      fortinet_fortios: "config system global\nset admintimeout 10\nend",
      arista_eos: "configure\nmanagement ssh\nidle-timeout 10\nexit\nwrite memory",
    },
  },
  {
    id: "NIST-AU-8",
    title: "Time Stamps (Authoritative Stratum NTP Synchronization)",
    framework: "nist_800_53",
    severity: "medium",
    controlGroupId: "CTRL-NTP-SYNC",
    description: "Synchronize internal device clocks to authoritative stratum time sources for audit fidelity.",
    frameworkRef: "NIST SP 800-53 Rev. 5 AU-8(1)",
    sourceNote: "NIST SP 800-53 Rev. 5, Control AU-8(1) (Synchronization with Authoritative Time Source)",
    evaluate: (p) => (p.ntpConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nntp server 10.14.0.1 prefer\nntp authenticate\nend\nwrite memory",
      juniper_junos: "set system ntp server 10.14.0.1 prefer\ncommit",
      palo_alto_panos: "set deviceconfig system ntp-servers primary-ntp-server 10.14.0.1\ncommit",
      sonic: "config ntp add 10.14.0.1",
      fortinet_fortios: "config system ntp\nset ntpsync enable\nset type custom\nend",
      arista_eos: "configure\nntp server 10.14.0.1 prefer\nwrite memory",
    },
  },
  {
    id: "NIST-AC-8",
    title: "System Use Notification (Legal Advisory Banner)",
    framework: "nist_800_53",
    severity: "low",
    controlGroupId: "CTRL-LOGIN-BANNER",
    description: "Display an approved federal system use notification message before granting user access.",
    frameworkRef: "NIST SP 800-53 Rev. 5 AC-8",
    sourceNote: "NIST SP 800-53 Rev. 5, Control AC-8 (System Use Notification)",
    evaluate: (p) => (p.loginBannerConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nbanner login ^C\nUS GOVERNMENT SYSTEM - AUTHORIZED ACCESS ONLY\n^C\nend\nwrite memory",
      juniper_junos: 'set system login message "US GOVERNMENT SYSTEM - AUTHORIZED ACCESS ONLY"\ncommit',
      palo_alto_panos: 'set deviceconfig system login-banner "US GOVERNMENT SYSTEM - AUTHORIZED ACCESS ONLY"\ncommit',
      sonic: 'config banner login "US GOVERNMENT SYSTEM - AUTHORIZED ACCESS ONLY"',
      fortinet_fortios: "config system global\nset pre-login-banner enable\nend",
      arista_eos: "configure\nbanner login\nUS GOVERNMENT SYSTEM - AUTHORIZED ACCESS ONLY\nEOF\nwrite memory",
    },
  },

  // ─── DISA STIG Controls ───
  {
    id: "STIG-NET-0001",
    title: "DoD STIG: Prohibit Unencrypted Telnet Protocol",
    framework: "disa_stig",
    severity: "critical",
    catRating: "CAT I",
    controlGroupId: "CTRL-TELNET-OFF",
    description: "The network device must not utilize unencrypted protocols for administrative sessions (DoD CAT I).",
    frameworkRef: "DISA STIG Rule SV-216960r856276_rule (SRG-NET-000018-RTR-000002)",
    sourceNote: "DISA Cisco Router STIG V-216960, CISC-RT-000010 (CAT I Finding)",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend\nwrite memory",
      juniper_junos: "delete system services telnet\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: "systemctl mask --now telnet.socket",
      fortinet_fortios: 'config system interface\nedit "port1"\nset allowaccess https ssh ping\nnext\nend',
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0002",
    title: "DoD STIG: Prohibit Clear-Text Web Management (HTTP)",
    framework: "disa_stig",
    severity: "critical",
    catRating: "CAT I",
    controlGroupId: "CTRL-HTTP-OFF",
    description: "The network device must disable unencrypted web management interfaces (DoD CAT I).",
    frameworkRef: "DISA STIG Rule SV-216960r856276_rule (SRG-NET-000018-RTR-000002)",
    sourceNote: "DISA Cisco Router STIG V-216960, CISC-RT-000010 (CAT I Finding)",
    evaluate: (p) => (p.httpServerEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno ip http server\nip http secure-server\nend\nwrite memory",
      juniper_junos: "delete system services web-management http\nset system services web-management https\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-http yes\ncommit",
      sonic: "systemctl stop nginx-http && systemctl disable nginx-http",
      fortinet_fortios: "config system global\nset admin-https-redirect enable\nend",
      arista_eos: "configure\nno management api http-commands\nprotocol https\nexit\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0003",
    title: "DoD STIG: Enforce SSHv2 Protocol Exclusively",
    framework: "disa_stig",
    severity: "high",
    catRating: "CAT II",
    controlGroupId: "CTRL-SSH-V2",
    description: "The network device must exclusively enforce SSH Version 2 with approved Diffie-Hellman exchanges (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216959r856275_rule (SRG-NET-000018-RTR-000001)",
    sourceNote: "DISA Cisco Router STIG V-216959, CISC-RT-000020 (CAT II Finding)",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend\nwrite memory",
      juniper_junos: "set system services ssh protocol-version v2\ncommit",
      palo_alto_panos: "set deviceconfig system ssh ciphers mgmt [ aes256-gcm aes256-ctr ]\ncommit",
      sonic: 'sonic-cli -c "configure terminal ; ip ssh version 2"',
      fortinet_fortios: "config system global\nset admin-ssh-v1 disable\nset strong-crypto enable\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0004",
    title: "DoD STIG: Cryptographic Local Password Storage",
    framework: "disa_stig",
    severity: "high",
    catRating: "CAT II",
    controlGroupId: "CTRL-PASS-ENCRYPT",
    description: "The network device must hash local passwords using FIPS-validated cryptographic algorithms (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216975r856291_rule (SRG-NET-000168-RTR-000078)",
    sourceNote: "DISA Cisco Router STIG V-216975, CISC-RT-000240 (CAT II Finding)",
    evaluate: (p) => (p.passwordEncryptionEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nservice password-encryption\nend\nwrite memory",
      juniper_junos: "set system login password-format sha512\ncommit",
      palo_alto_panos: "set mgt-config users secadmin password\ncommit",
      sonic: "passwd -e admin",
      fortinet_fortios: "config system global\nset strong-crypto enable\nend",
      arista_eos: "configure\nservice password-encryption\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0005",
    title: "DoD STIG: Centralized TACACS+/RADIUS Authorization",
    framework: "disa_stig",
    severity: "high",
    catRating: "CAT II",
    controlGroupId: "CTRL-AAA-AUTH",
    description: "The network device must authenticate and authorize administrative users against centralized AAA (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216957r856273_rule (SRG-NET-000015-RTR-000001)",
    sourceNote: "DISA Cisco Router STIG V-216957, CISC-RT-000030 (CAT II Finding)",
    evaluate: (p) => (p.aaaAuthEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\naaa new-model\naaa authentication login default group tacacs+ local\nend\nwrite memory",
      juniper_junos: "set system authentication-order [ tacplus radius password ]\ncommit",
      palo_alto_panos: "set shared authentication-profile TACACS-AUTH method tacacs-plus\ncommit",
      sonic: "config aaa authentication login tacacs+ local",
      fortinet_fortios: 'config user tacacs+\nedit "dod_tacacs"\nset server "10.14.5.10"\nnext\nend',
      arista_eos: "configure\naaa authentication login default group tacacs+ local\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0006",
    title: "DoD STIG: Enforce SNMPv3 with AuthPriv Cryptography",
    framework: "disa_stig",
    severity: "high",
    catRating: "CAT II",
    controlGroupId: "CTRL-SNMP-V3",
    description: "The network device must utilize SNMPv3 with FIPS-validated encryption (authPriv) for telemetry (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216965r856281_rule (SRG-NET-000131-RTR-000035)",
    sourceNote: "DISA Cisco Router STIG V-216965, CISC-RT-000200 (CAT II Finding)",
    evaluate: (p) => (p.snmpVersion === "v3" ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno snmp-server community public\nsnmp-server group STIG_GRP v3 priv\nend\nwrite memory",
      juniper_junos: "delete snmp community\nset snmp v3 usm local-engine user stigadmin authentication-sha\ncommit",
      palo_alto_panos: "set deviceconfig system snmp-setting snmp-version-v3 user stigadmin authpwd <pwd> privpwd <pwd>\ncommit",
      sonic: "config snmp user add stigadmin SHA <key> AES <key>",
      fortinet_fortios: 'config system snmp user\nedit "stigadmin"\nset security-level auth-priv\nnext\nend',
      arista_eos: "configure\nsnmp-server group STIG_GRP v3 auth\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0007",
    title: "DoD STIG: Forward Security Events via Remote Syslog",
    framework: "disa_stig",
    severity: "high",
    catRating: "CAT II",
    controlGroupId: "CTRL-SYSLOG-SIEM",
    description: "The network device must send audit records to a central audit repository in real time (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216970r856286_rule (SRG-NET-000333-RTR-000098)",
    sourceNote: "DISA Cisco Router STIG V-216970, CISC-RT-000100 (CAT II Finding)",
    evaluate: (p) => (p.syslogServers !== null ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nlogging host 10.14.5.50\nend\nwrite memory",
      juniper_junos: "set system syslog host 10.14.5.50 any warning facility-override local5\ncommit",
      palo_alto_panos: "set shared log-settings syslog SIEM server 10.14.5.50 port 514\ncommit",
      sonic: "config syslog add 10.14.5.50",
      fortinet_fortios: 'config log syslogd setting\nset status enable\nset server "10.14.5.50"\nend',
      arista_eos: "configure\nlogging host 10.14.5.50\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0008",
    title: "DoD STIG: Terminate Inactive Sessions Within 10-15 Minutes",
    framework: "disa_stig",
    severity: "medium",
    catRating: "CAT II",
    controlGroupId: "CTRL-IDLE-TIMEOUT",
    description: "The network device must terminate an administrative session after a defined inactivity window (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216962r856278_rule (SRG-NET-000113-RTR-000027)",
    sourceNote: "DISA Cisco Router STIG V-216962, CISC-RT-000060 (CAT II Finding)",
    evaluate: (p) => (p.sessionIdleTimeoutMinutes !== null && Number(p.sessionIdleTimeoutMinutes) <= 15 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline con 0\nexec-timeout 10 0\nline vty 0 15\nexec-timeout 10 0\nend\nwrite memory",
      juniper_junos: "set system login idle-timeout 10\ncommit",
      palo_alto_panos: "set deviceconfig system idle-timeout 10\ncommit",
      sonic: "config ssh idle-timeout 600",
      fortinet_fortios: "config system global\nset admintimeout 10\nend",
      arista_eos: "configure\nmanagement ssh\nidle-timeout 10\nexit\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0009",
    title: "DoD STIG: Synchronize Clocks to Designated DoD Time Server",
    framework: "disa_stig",
    severity: "low",
    catRating: "CAT III",
    controlGroupId: "CTRL-NTP-SYNC",
    description: "The network device must synchronize its internal clock with designated DoD authoritative NTP servers (DoD CAT III).",
    frameworkRef: "DISA STIG Rule SV-216972r856288_rule (SRG-NET-000168-RTR-000077)",
    sourceNote: "DISA Cisco Router STIG V-216972, CISC-RT-000110 (CAT III Finding)",
    evaluate: (p) => (p.ntpConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nntp server 10.14.0.1 prefer\nntp authenticate\nend\nwrite memory",
      juniper_junos: "set system ntp server 10.14.0.1 prefer\ncommit",
      palo_alto_panos: "set deviceconfig system ntp-servers primary-ntp-server 10.14.0.1\ncommit",
      sonic: "config ntp add 10.14.0.1",
      fortinet_fortios: "config system ntp\nset ntpsync enable\nset type custom\nend",
      arista_eos: "configure\nntp server 10.14.0.1 prefer\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0010",
    title: "DoD STIG: Mandatory Standard Notice and Consent Banner",
    framework: "disa_stig",
    severity: "medium",
    catRating: "CAT II",
    controlGroupId: "CTRL-LOGIN-BANNER",
    description: "The network device must display the approved DoD warning banner prior to granting access (DoD CAT II).",
    frameworkRef: "DISA STIG Rule SV-216964r856280_rule (SRG-NET-000041-RTR-000008)",
    sourceNote: "DISA Cisco Router STIG V-216964, CISC-RT-000050 (CAT II Finding)",
    evaluate: (p) => (p.loginBannerConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nbanner login ^C\nYou are accessing a U.S. Government Information System provided for USG-authorized use only.\n^C\nend\nwrite memory",
      juniper_junos: 'set system login message "You are accessing a U.S. Government Information System provided for USG-authorized use only."\ncommit',
      palo_alto_panos: 'set deviceconfig system login-banner "You are accessing a U.S. Government Information System provided for USG-authorized use only."\ncommit',
      sonic: 'config banner login "You are accessing a U.S. Government Information System provided for USG-authorized use only."',
      fortinet_fortios: "config system global\nset pre-login-banner enable\nend",
      arista_eos: "configure\nbanner login\nYou are accessing a U.S. Government Information System provided for USG-authorized use only.\nEOF\nwrite memory",
    },
  },

  // ─── ISO 27001:2022 Controls ───
  {
    id: "ISO-A.8.20",
    title: "Network Controls (Encrypted Remote Management - SSHv2)",
    framework: "iso_27001",
    severity: "critical",
    controlGroupId: "CTRL-SSH-V2",
    description: "Networks must be secured, managed, and controlled to protect information in systems and applications.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.20",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.20 (Network Security - Remote Management Encryption)",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend\nwrite memory",
      juniper_junos: "set system services ssh protocol-version v2\ncommit",
      palo_alto_panos: "set deviceconfig system ssh ciphers mgmt [ aes256-gcm aes256-ctr ]\ncommit",
      sonic: 'sonic-cli -c "configure terminal ; ip ssh version 2"',
      fortinet_fortios: "config system global\nset admin-ssh-v1 disable\nset strong-crypto enable\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.21",
    title: "Security of Network Services (Disable Insecure Telnet)",
    framework: "iso_27001",
    severity: "critical",
    controlGroupId: "CTRL-TELNET-OFF",
    description: "Security mechanisms, service levels and service requirements of network services must be identified and implemented.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.21",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.21 (Security of Network Services - Disable Insecure Protocols)",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend\nwrite memory",
      juniper_junos: "delete system services telnet\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: "systemctl mask --now telnet.socket",
      fortinet_fortios: 'config system interface\nedit "port1"\nset allowaccess https ssh ping\nnext\nend',
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.9",
    title: "Configuration Management (Terminate Plaintext Web Interfaces)",
    framework: "iso_27001",
    severity: "high",
    controlGroupId: "CTRL-HTTP-OFF",
    description: "Configurations, including security configurations, of hardware, software, services and networks must be established and monitored.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.9",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.9 (Configuration Management - Secure Baseline Hardening)",
    evaluate: (p) => (p.httpServerEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno ip http server\nip http secure-server\nend\nwrite memory",
      juniper_junos: "delete system services web-management http\nset system services web-management https\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-http yes\ncommit",
      sonic: "systemctl stop nginx-http && systemctl disable nginx-http",
      fortinet_fortios: "config system global\nset admin-https-redirect enable\nend",
      arista_eos: "configure\nno management api http-commands\nprotocol https\nexit\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.24",
    title: "Use of Cryptography (Local Credential Storage Encryption)",
    framework: "iso_27001",
    severity: "high",
    controlGroupId: "CTRL-PASS-ENCRYPT",
    description: "Rules for the effective use of cryptography, including cryptographic key management, must be defined and implemented.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.24",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.24 (Use of Cryptography - Credential Storage)",
    evaluate: (p) => (p.passwordEncryptionEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nservice password-encryption\nend\nwrite memory",
      juniper_junos: "set system login password-format sha512\ncommit",
      palo_alto_panos: "set mgt-config users secadmin password\ncommit",
      sonic: "passwd -e admin",
      fortinet_fortios: "config system global\nset strong-crypto enable\nend",
      arista_eos: "configure\nservice password-encryption\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.5",
    title: "Secure Authentication (Centralized AAA Access Control)",
    framework: "iso_27001",
    severity: "high",
    controlGroupId: "CTRL-AAA-AUTH",
    description: "Secure authentication technologies and procedures must be implemented based on information access restrictions.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.5",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.5 (Secure Authentication - Centralized Directory Services)",
    evaluate: (p) => (p.aaaAuthEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\naaa new-model\naaa authentication login default group tacacs+ local\nend\nwrite memory",
      juniper_junos: "set system authentication-order [ tacplus radius password ]\ncommit",
      palo_alto_panos: "set shared authentication-profile TACACS-AUTH method tacacs-plus\ncommit",
      sonic: "config aaa authentication login tacacs+ local",
      fortinet_fortios: 'config user tacacs+\nedit "iso_tacacs"\nset server "10.14.5.10"\nnext\nend',
      arista_eos: "configure\naaa authentication login default group tacacs+ local\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.24-SNMP",
    title: "Use of Cryptography (Mandate Secure SNMPv3 Authentication)",
    framework: "iso_27001",
    severity: "high",
    controlGroupId: "CTRL-SNMP-V3",
    description: "Rules for cryptographic protection must be applied to telemetry monitoring and management protocols.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.24",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.24 (Use of Cryptography - Management Protocols)",
    evaluate: (p) => (p.snmpVersion === "v3" ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno snmp-server community public\nsnmp-server group ISO_GRP v3 priv\nend\nwrite memory",
      juniper_junos: "delete snmp community\nset snmp v3 usm local-engine user isooper authentication-sha\ncommit",
      palo_alto_panos: "set deviceconfig system snmp-setting snmp-version-v3 user isooper authpwd <pwd> privpwd <pwd>\ncommit",
      sonic: "config snmp user add isooper SHA <key> AES <key>",
      fortinet_fortios: 'config system snmp user\nedit "isooper"\nset security-level auth-priv\nnext\nend',
      arista_eos: "configure\nsnmp-server group ISO_GRP v3 auth\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.15",
    title: "Logging (Forward Security Events to Tamper-Resistant SIEM)",
    framework: "iso_27001",
    severity: "high",
    controlGroupId: "CTRL-SYSLOG-SIEM",
    description: "Logs recording security events, activities, and exceptions must be produced, stored, protected and analyzed.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.15",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.15 (Logging - Centralized Collection & Monitoring)",
    evaluate: (p) => (p.syslogServers !== null ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nlogging host 10.14.5.50\nlogging trap notifications\nend\nwrite memory",
      juniper_junos: "set system syslog host 10.14.5.50 any warning facility-override local5\ncommit",
      palo_alto_panos: "set shared log-settings syslog SIEM server 10.14.5.50 port 514\ncommit",
      sonic: "config syslog add 10.14.5.50",
      fortinet_fortios: 'config log syslogd setting\nset status enable\nset server "10.14.5.50"\nend',
      arista_eos: "configure\nlogging host 10.14.5.50\nwrite memory",
    },
  },
  {
    id: "ISO-A.5.15",
    title: "Access Control (Automatically Terminate Inactive Sessions)",
    framework: "iso_27001",
    severity: "medium",
    controlGroupId: "CTRL-IDLE-TIMEOUT",
    description: "Rules to control physical and logical access must mandate terminating unattended administrative sessions.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.5.15",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.5.15 (Access Control - Session Inactivity Lockout)",
    evaluate: (p) => (p.sessionIdleTimeoutMinutes !== null && Number(p.sessionIdleTimeoutMinutes) <= 15 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline con 0\nexec-timeout 10 0\nline vty 0 15\nexec-timeout 10 0\nend\nwrite memory",
      juniper_junos: "set system login idle-timeout 10\ncommit",
      palo_alto_panos: "set deviceconfig system idle-timeout 10\ncommit",
      sonic: "config ssh idle-timeout 600",
      fortinet_fortios: "config system global\nset admintimeout 10\nend",
      arista_eos: "configure\nmanagement ssh\nidle-timeout 10\nexit\nwrite memory",
    },
  },
  {
    id: "ISO-A.8.17",
    title: "Clock Synchronization (Synchronize with Authoritative NTP Sources)",
    framework: "iso_27001",
    severity: "medium",
    controlGroupId: "CTRL-NTP-SYNC",
    description: "The clocks of information processing systems must be synchronized to approved authoritative time sources.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.17",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.8.17 (Clock Synchronization)",
    evaluate: (p) => (p.ntpConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nntp server 10.14.0.1 prefer\nntp authenticate\nend\nwrite memory",
      juniper_junos: "set system ntp server 10.14.0.1 prefer\ncommit",
      palo_alto_panos: "set deviceconfig system ntp-servers primary-ntp-server 10.14.0.1\ncommit",
      sonic: "config ntp add 10.14.0.1",
      fortinet_fortios: "config system ntp\nset ntpsync enable\nset type custom\nend",
      arista_eos: "configure\nntp server 10.14.0.1 prefer\nwrite memory",
    },
  },
  {
    id: "ISO-A.5.15-BANNER",
    title: "Access Control (Authorized Notice and Login Banner)",
    framework: "iso_27001",
    severity: "low",
    controlGroupId: "CTRL-LOGIN-BANNER",
    description: "Rules for access control require presenting an official notice of authorized access restrictions.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.5.15",
    sourceNote: "ISO/IEC 27001:2022 Annex A, Control A.5.15 (Access Control - Advisory Warning Notice)",
    evaluate: (p) => (p.loginBannerConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nbanner login ^C\nAUTHORIZED USERS ONLY - ALL ACCESS MONITORED\n^C\nend\nwrite memory",
      juniper_junos: 'set system login message "AUTHORIZED USERS ONLY - ALL ACCESS MONITORED"\ncommit',
      palo_alto_panos: 'set deviceconfig system login-banner "AUTHORIZED USERS ONLY - ALL ACCESS MONITORED"\ncommit',
      sonic: 'config banner login "AUTHORIZED USERS ONLY - ALL ACCESS MONITORED"',
      fortinet_fortios: "config system global\nset pre-login-banner enable\nend",
      arista_eos: "configure\nbanner login\nAUTHORIZED USERS ONLY - ALL ACCESS MONITORED\nEOF\nwrite memory",
    },
  },
];
