// src/engine/rules.ts
// Compliance Rule Catalog across CIS v8, NIST 800-53, DISA STIG, and ISO 27001
// Each rule evaluates ONLY NormalizedConfig["parameters"] and maps controlGroupId for deduplication (§6.4)

import { ComplianceRule, NormalizedConfig } from "../types/canonical";

export const COMPLIANCE_RULES: ComplianceRule[] = [
  // ─── CIS Controls v8 ───
  {
    id: "CIS-NET-1.1.1",
    title: "Enforce SSHv2 Protocol Exclusively",
    framework: "cis_v8",
    severity: "critical",
    controlGroupId: "CTRL-SSH-V2",
    description: "Legacy SSHv1 protocol possesses cryptographic weaknesses permitting session interception and MITM.",
    frameworkRef: "CIS Controls v8 Safeguard 4.1",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : p.sshVersion === null ? "fail" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend\nwrite memory",
      juniper_junos: "set system services ssh protocol-version v2\ncommit and-quit",
      palo_alto_panos: "set deviceconfig system ssh-version 2\ncommit",
      sonic: 'sonic-cli -c "config ssh protocol 2"',
      fortinet_fortios: "config system global\nset admin-ssh-port 22\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.1.2",
    title: "Disable Insecure Telnet Daemon",
    framework: "cis_v8",
    severity: "critical",
    controlGroupId: "CTRL-TELNET-OFF",
    description: "Telnet transmits administrative credentials and session commands in plaintext over the wire.",
    frameworkRef: "CIS Controls v8 Safeguard 4.2",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : p.telnetEnabled === true ? "fail" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend\nwrite memory",
      juniper_junos: "delete system services telnet\ncommit and-quit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: 'sonic-cli -c "config telnet disable"',
      fortinet_fortios: "config system global\nset admin-telnet-service disable\nend",
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.1.3",
    title: "Disable Plaintext HTTP Web Management",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-HTTP-OFF",
    description: "Unencrypted web management consoles expose session cookies and credentials to eavesdropping.",
    frameworkRef: "CIS Controls v8 Safeguard 4.3",
    evaluate: (p) => (p.httpServerEnabled === false ? "pass" : p.httpServerEnabled === true ? "fail" : "pass"),
    remediation: {
      cisco_ios: "configure terminal\nno ip http server\nip http secure-server\nend\nwrite memory",
      juniper_junos: "delete system services web-management http\nset system services web-management https port 443\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-http yes\ncommit",
      sonic: 'systemctl stop nginx-http && systemctl disable nginx-http',
      fortinet_fortios: "config system global\nset admin-http-service disable\nset admin-sport 8443\nend",
      arista_eos: "configure\nno management api http-commands\nprotocol https\nexit\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.1.4",
    title: "Enforce Strong Local Password Encryption",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-PASS-ENCRYPT",
    description: "Pre-shared secrets and local operator passwords must be secured with irreversible cryptographic ciphers.",
    frameworkRef: "CIS Controls v8 Safeguard 5.2",
    evaluate: (p) => (p.passwordEncryptionEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nservice password-encryption\nenable secret 9 $9$e7xW$SECURE\nend\nwrite memory",
      juniper_junos: "set system root-authentication plain-text-password\ncommit",
      palo_alto_panos: "set mgt-config users secadmin password\ncommit",
      sonic: 'chage -M 90 admin && passwd -e admin',
      fortinet_fortios: "config system global\nset strong-crypto enable\nend",
      arista_eos: "configure\nservice password-encryption\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.2.1",
    title: "Centralized AAA Authentication Enforcement",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-AAA-AUTH",
    description: "Network devices must defer administrative credential verification to centralized TACACS+ or RADIUS.",
    frameworkRef: "CIS Controls v8 Safeguard 6.1",
    evaluate: (p) => (p.aaaAuthEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\naaa new-model\naaa authentication login default group tacacs+ local\nend",
      juniper_junos: "set system authentication-order [ tacplus radius password ]\ncommit",
      palo_alto_panos: "set shared authentication-profile RADIUS-AUTH method radius\ncommit",
      sonic: 'config aaa authentication login tacacs+ local',
      fortinet_fortios: "config system admin\nedit secadmin\nset accprofile super_admin\nnext\nend",
      arista_eos: "configure\naaa authentication login default group tacacs+ local\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.2.2",
    title: "SNMP Protocol Restricted to v3 authPriv",
    framework: "cis_v8",
    severity: "critical",
    controlGroupId: "CTRL-SNMP-V3",
    description: "Legacy SNMPv1/v2c relies on cleartext community strings subject to replay and reconnaissance.",
    frameworkRef: "CIS Controls v8 Safeguard 4.8",
    evaluate: (p) => (p.snmpVersion === "v3" ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nno snmp-server community public\nsnmp-server group SECGROUP v3 priv\nend",
      juniper_junos: "delete snmp community\nset snmp v3 usm local-engine user admin-v3 authentication-sha\ncommit",
      palo_alto_panos: "set deviceconfig system snmp-setting snmp-version v3\ncommit",
      sonic: 'sonic-cli -c "config snmp version v3"',
      fortinet_fortios: "config system snmp sysinfo\nset status enable\nend",
      arista_eos: "configure\nsnmp-server group SECGROUP v3 auth\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.3.1",
    title: "Remote Centralized Syslog Forwarding",
    framework: "cis_v8",
    severity: "high",
    controlGroupId: "CTRL-SYSLOG-SIEM",
    description: "Security telemetry and event logs must be streamed continuously to the SIEM cluster.",
    frameworkRef: "CIS Controls v8 Safeguard 8.2",
    evaluate: (p) => (p.syslogServers !== null ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nlogging host 10.14.5.50\nlogging trap notifications\nend",
      juniper_junos: "set system syslog host 10.14.5.50 any warning\ncommit",
      palo_alto_panos: "set shared log-settings syslog SIEM server 10.14.5.50 port 514\ncommit",
      sonic: 'config syslog add 10.14.5.50',
      fortinet_fortios: "config log syslogd setting\nset status enable\nset server 10.14.5.50\nend",
      arista_eos: "configure\nlogging host 10.14.5.50\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.3.2",
    title: "Terminal Session Idle Timeout Lockout (≤ 15 min)",
    framework: "cis_v8",
    severity: "medium",
    controlGroupId: "CTRL-IDLE-TIMEOUT",
    description: "Unattended management sessions must be terminated automatically after 15 minutes.",
    frameworkRef: "CIS Controls v8 Safeguard 4.11",
    evaluate: (p) => (p.sessionIdleTimeoutMinutes !== null && Number(p.sessionIdleTimeoutMinutes) <= 15 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline con 0\nexec-timeout 10 0\nline vty 0 15\nexec-timeout 10 0\nend",
      juniper_junos: "set system login idle-timeout 10\ncommit",
      palo_alto_panos: "set deviceconfig system idle-timeout 10\ncommit",
      sonic: 'config ssh idle-timeout 600',
      fortinet_fortios: "config system global\nset admintimeout 10\nend",
      arista_eos: "configure\nmanagement ssh\nidle-timeout 10\nexit\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.4.1",
    title: "Cryptographic NTP Time Synchronization",
    framework: "cis_v8",
    severity: "medium",
    controlGroupId: "CTRL-NTP-SYNC",
    description: "Audit trail defensibility requires all devices synchronize against trusted time references.",
    frameworkRef: "CIS Controls v8 Safeguard 8.4",
    evaluate: (p) => (p.ntpConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nntp server 10.14.0.1 prefer\nntp authenticate\nend",
      juniper_junos: "set system ntp server 10.14.0.1\ncommit",
      palo_alto_panos: "set deviceconfig system ntp-servers primary-ntp-server 10.14.0.1\ncommit",
      sonic: 'config ntp add 10.14.0.1',
      fortinet_fortios: "config system ntp\nset ntpsync enable\nset type custom\nend",
      arista_eos: "configure\nntp server 10.14.0.1 prefer\nwrite memory",
    },
  },
  {
    id: "CIS-NET-1.4.2",
    title: "Authorized Login Notice / Banner Configuration",
    framework: "cis_v8",
    severity: "low",
    controlGroupId: "CTRL-LOGIN-BANNER",
    description: "Statutory notice of authorized government access must be presented before login.",
    frameworkRef: "CIS Controls v8 Safeguard 4.10",
    evaluate: (p) => (p.loginBannerConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nbanner login ^C\nRESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY\n^C\nend",
      juniper_junos: 'set system login message "RESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY"\ncommit',
      palo_alto_panos: 'set deviceconfig system login-banner "RESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY"\ncommit',
      sonic: 'config banner login "RESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY"',
      fortinet_fortios: "config system global\nset pre-login-banner enable\nend",
      arista_eos: "configure\nbanner login\nRESTRICTED SYSTEM - AUTHORIZED ACCESS ONLY\nEOF\nwrite memory",
    },
  },

  // ─── NIST SP 800-53 Rev. 5 Controls ───
  {
    id: "NIST-AC-17",
    title: "Remote Access Encryption Protocol (SSHv2)",
    framework: "nist_800_53",
    severity: "critical",
    controlGroupId: "CTRL-SSH-V2", // Same underlying control as CIS-NET-1.1.1!
    description: "NIST AC-17 mandates FIPS-approved cryptographic protocols for all remote network maintenance.",
    frameworkRef: "NIST SP 800-53 AC-17(2)",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend",
      juniper_junos: "set system services ssh protocol-version v2\ncommit",
      palo_alto_panos: "set deviceconfig system ssh-version 2\ncommit",
      sonic: 'sonic-cli -c "config ssh protocol 2"',
      fortinet_fortios: "config system global\nset admin-ssh-port 22\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit",
    },
  },
  {
    id: "NIST-SC-8",
    title: "Transmission Confidentiality (Ban Insecure Telnet)",
    framework: "nist_800_53",
    severity: "critical",
    controlGroupId: "CTRL-TELNET-OFF", // Same underlying control as CIS-NET-1.1.2!
    description: "Prohibit transmission of confidential data over unencrypted cleartext transport daemons.",
    frameworkRef: "NIST SP 800-53 SC-8(1)",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend",
      juniper_junos: "delete system services telnet\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: 'sonic-cli -c "config telnet disable"',
      fortinet_fortios: "config system global\nset admin-telnet-service disable\nend",
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "NIST-AU-3",
    title: "Content of Audit Records (Centralized SIEM Syslog)",
    framework: "nist_800_53",
    severity: "high",
    controlGroupId: "CTRL-SYSLOG-SIEM", // Same underlying control as CIS-NET-1.3.1!
    description: "Stream system activity, account modifications, and boundary alerts to remote audit repository.",
    frameworkRef: "NIST SP 800-53 AU-3(1)",
    evaluate: (p) => (p.syslogServers !== null ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nlogging host 10.14.5.50\nend",
      juniper_junos: "set system syslog host 10.14.5.50 any warning\ncommit",
      palo_alto_panos: "set shared log-settings syslog SIEM server 10.14.5.50 port 514\ncommit",
      sonic: 'config syslog add 10.14.5.50',
      fortinet_fortios: "config log syslogd setting\nset server 10.14.5.50\nend",
      arista_eos: "configure\nlogging host 10.14.5.50\nwrite memory",
    },
  },
  {
    id: "NIST-AC-11",
    title: "Device Session Lockout (≤ 15 min Idle Timeout)",
    framework: "nist_800_53",
    severity: "medium",
    controlGroupId: "CTRL-IDLE-TIMEOUT", // Same underlying control as CIS-NET-1.3.2!
    description: "Prevent unauthorized physical or remote terminal takeover by enforcing inactivity lockouts.",
    frameworkRef: "NIST SP 800-53 AC-11",
    evaluate: (p) => (p.sessionIdleTimeoutMinutes !== null && Number(p.sessionIdleTimeoutMinutes) <= 15 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\nexec-timeout 10 0\nend",
      juniper_junos: "set system login idle-timeout 10\ncommit",
      palo_alto_panos: "set deviceconfig system idle-timeout 10\ncommit",
      sonic: 'config ssh idle-timeout 600',
      fortinet_fortios: "config system global\nset admintimeout 10\nend",
      arista_eos: "configure\nmanagement ssh\nidle-timeout 10\nexit",
    },
  },

  // ─── DISA STIG Controls ───
  {
    id: "STIG-NET-0001",
    title: "DoD STIG: Telnet Insecure Daemon Prohibition",
    framework: "disa_stig",
    severity: "critical",
    controlGroupId: "CTRL-TELNET-OFF", // Deduplicates with CIS & NIST!
    description: "The network device must not utilize unencrypted protocols for device administration.",
    frameworkRef: "DISA STIG Rule SV-216503r601684_rule",
    evaluate: (p) => (p.telnetEnabled === false ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nline vty 0 15\ntransport input ssh\nend",
      juniper_junos: "delete system services telnet\ncommit",
      palo_alto_panos: "set deviceconfig system service disable-telnet yes\ncommit",
      sonic: 'sonic-cli -c "config telnet disable"',
      fortinet_fortios: "config system global\nset admin-telnet-service disable\nend",
      arista_eos: "configure\nno management telnet\nwrite memory",
    },
  },
  {
    id: "STIG-NET-0002",
    title: "DoD STIG: Mandatory Standard Login Warning Banner",
    framework: "disa_stig",
    severity: "high",
    controlGroupId: "CTRL-LOGIN-BANNER", // Deduplicates with CIS!
    description: "The network device must display the approved DoD/Government warning banner prior to grant of access.",
    frameworkRef: "DISA STIG Rule SV-216504r601685_rule",
    evaluate: (p) => (p.loginBannerConfigured === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nbanner login ^C\nAUTHORIZED ACCESS ONLY - ALL ACTIVITY MONITORED\n^C\nend",
      juniper_junos: 'set system login message "AUTHORIZED ACCESS ONLY - ALL ACTIVITY MONITORED"\ncommit',
      palo_alto_panos: 'set deviceconfig system login-banner "AUTHORIZED ACCESS ONLY - ALL ACTIVITY MONITORED"\ncommit',
      sonic: 'config banner login "AUTHORIZED ACCESS ONLY - ALL ACTIVITY MONITORED"',
      fortinet_fortios: "config system global\nset pre-login-banner enable\nend",
      arista_eos: "configure\nbanner login\nAUTHORIZED ACCESS ONLY - ALL ACTIVITY MONITORED\nEOF\nwrite memory",
    },
  },

  // ─── ISO 27001:2022 Controls ───
  {
    id: "ISO-A.8.20",
    title: "Network Security Controls (Encrypted Remote Management)",
    framework: "iso_27001",
    severity: "critical",
    controlGroupId: "CTRL-SSH-V2", // Deduplicates with CIS & NIST!
    description: "Networks must be secured and monitored to protect information in systems and applications.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.20",
    evaluate: (p) => (p.sshVersion === 2 ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nip ssh version 2\nend",
      juniper_junos: "set system services ssh protocol-version v2\ncommit",
      palo_alto_panos: "set deviceconfig system ssh-version 2\ncommit",
      sonic: 'sonic-cli -c "config ssh protocol 2"',
      fortinet_fortios: "config system global\nset admin-ssh-port 22\nend",
      arista_eos: "configure\nmanagement ssh\nprotocol version 2\nexit",
    },
  },
  {
    id: "ISO-A.8.24",
    title: "Use of Cryptography (Password Storage & Key Material)",
    framework: "iso_27001",
    severity: "high",
    controlGroupId: "CTRL-PASS-ENCRYPT", // Deduplicates with CIS!
    description: "Rules for the effective use of cryptography, including cryptographic key management, must be defined.",
    frameworkRef: "ISO/IEC 27001:2022 Control A.8.24",
    evaluate: (p) => (p.passwordEncryptionEnabled === true ? "pass" : "fail"),
    remediation: {
      cisco_ios: "configure terminal\nservice password-encryption\nend",
      juniper_junos: "set system root-authentication plain-text-password\ncommit",
      palo_alto_panos: "set mgt-config users secadmin password\ncommit",
      sonic: 'chage -M 90 admin',
      fortinet_fortios: "config system global\nset strong-crypto enable\nend",
      arista_eos: "configure\nservice password-encryption\nwrite memory",
    },
  },
];
